//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeMapFIlter.resources.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeMapFIlter.resources.lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by: Mussk.
        /// </summary>
        public static string About_CreatedByLabel {
            get {
                return ResourceManager.GetString("About_CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font by: exlijbris.nl.
        /// </summary>
        public static string About_FontByLabel {
            get {
                return ResourceManager.GetString("About_FontByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found bug?.
        /// </summary>
        public static string About_FoundBugLabel {
            get {
                return ResourceManager.GetString("About_FoundBugLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string About_VersionLabel {
            get {
                return ResourceManager.GetString("About_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_WindowName {
            get {
                return ResourceManager.GetString("About_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All mods:.
        /// </summary>
        public static string AllModsLabel {
            get {
                return ResourceManager.GetString("AllModsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorWindowName {
            get {
                return ResourceManager.GetString("ErrorWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey:.
        /// </summary>
        public static string HotkeyLabel {
            get {
                return ResourceManager.GetString("HotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Class: Maps.
        /// </summary>
        public static string ItemClassString {
            get {
                return ResourceManager.GetString("ItemClassString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string JsonParseHiddenString {
            get {
                return ResourceManager.GetString("JsonParseHiddenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! After changing the language for the first time mods should be seleced again..
        /// </summary>
        public static string LanguageComboBoxTooltip {
            get {
                return ResourceManager.GetString("LanguageComboBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (restart needed):.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Window.
        /// </summary>
        public static string MapWindowName {
            get {
                return ResourceManager.GetString("MapWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods:.
        /// </summary>
        public static string ModsLabel {
            get {
                return ResourceManager.GetString("ModsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods selection.
        /// </summary>
        public static string ModsSelectionLabel {
            get {
                return ResourceManager.GetString("ModsSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load map mods. Check your Internet connection and try again.
        /// </summary>
        public static string NoInternetMessage {
            get {
                return ResourceManager.GetString("NoInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Updates.
        /// </summary>
        public static string NotifyIconCheckUpdates {
            get {
                return ResourceManager.GetString("NotifyIconCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string NotifyIconExit {
            get {
                return ResourceManager.GetString("NotifyIconExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Page.
        /// </summary>
        public static string NotifyIconGitHubPage {
            get {
                return ResourceManager.GetString("NotifyIconGitHubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NotifyIconSettings {
            get {
                return ResourceManager.GetString("NotifyIconSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string OtherSettingsLabel {
            get {
                return ResourceManager.GetString("OtherSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pathofexile.fandom.com/api.php?action=cargoquery&amp;tables=mods,spawn_weights&amp;join_on=mods._pageID=spawn_weights._pageID&amp;fields=stat_text&amp;where=mods.domain=5%20AND%20NOT%20mods.name=%22%22%20AND%20spawn_weights.weight%20%3E%200&amp;limit=500&amp;format=json.
        /// </summary>
        public static string PoeWikiMapModsURL {
            get {
                return ResourceManager.GetString("PoeWikiMapModsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity: +{0}%.
        /// </summary>
        public static string QuantityTextBox {
            get {
                return ResourceManager.GetString("QuantityTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mods:.
        /// </summary>
        public static string SelectedModsLabel {
            get {
                return ResourceManager.GetString("SelectedModsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SettingsAllModsSearchPlaceholder {
            get {
                return ResourceManager.GetString("SettingsAllModsSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow {
            get {
                return ResourceManager.GetString("SettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound signal:.
        /// </summary>
        public static string SoundSignalLabel {
            get {
                return ResourceManager.GetString("SoundSignalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier: .
        /// </summary>
        public static string TierTextBox {
            get {
                return ResourceManager.GetString("TierTextBox", resourceCulture);
            }
        }
    }
}
